"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const hundi_controller_1 = require("../controllers/hundi.controller");
const hundiTracking_controller_1 = require("../controllers/hundiTracking.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const router = (0, express_1.Router)();
router.use(auth_middleware_1.authenticate);
router.get('/roles', hundi_controller_1.getOrgRoles);
router.get('/item-units', hundi_controller_1.getItemUnits);
router.post('/item-units/delete', (0, auth_middleware_1.requirePermission)('hundi_module', 4), hundi_controller_1.deleteItemUnit);
router.get('/witness-suggestions/:templeId', hundi_controller_1.getWitnessSuggestions);
router.get('/master', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundi_controller_1.getMasterHundis);
router.post('/master', (0, auth_middleware_1.requirePermission)('hundi_module', 2), hundi_controller_1.createMasterHundi);
router.delete('/master/:id', (0, auth_middleware_1.requirePermission)('hundi_module', 4), hundi_controller_1.deleteMasterHundi);
router.get('/denominations', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundi_controller_1.getDenominations);
router.post('/denominations', (0, auth_middleware_1.requirePermission)('hundi_module', 2), hundi_controller_1.createDenomination);
router.put('/denominations/:id/image', (0, auth_middleware_1.requirePermission)('hundi_module', 2), hundi_controller_1.uploadDenominationImage);
router.delete('/denominations/:id/image', (0, auth_middleware_1.requirePermission)('hundi_module', 3), hundi_controller_1.deleteDenominationImage);
router.delete('/denominations/:id', (0, auth_middleware_1.requirePermission)('hundi_module', 4), hundi_controller_1.deleteDenomination);
router.get('/bank-lookup/:ifsc', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundiTracking_controller_1.lookupIfsc);
router.get('/bank-details', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundiTracking_controller_1.getBankDetails);
router.post('/bank-details', (0, auth_middleware_1.requirePermission)('hundi_module', 2), hundiTracking_controller_1.createBankDetail);
router.put('/bank-details/:id', (0, auth_middleware_1.requirePermission)('hundi_module', 3), hundiTracking_controller_1.updateBankDetail);
router.delete('/bank-details/:id', (0, auth_middleware_1.requirePermission)('hundi_module', 4), hundiTracking_controller_1.deleteBankDetail);
router.get('/tracking/status', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundiTracking_controller_1.getTrackingStatus);
router.get('/tracking/list', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundiTracking_controller_1.getTrackingList);
router.get('/tracking/:hundiId', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundiTracking_controller_1.getTrackingByHundi);
router.post('/tracking', (0, auth_middleware_1.requirePermission)('hundi_module', 2), hundiTracking_controller_1.createTracking);
router.get('/', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundi_controller_1.getAllHundis);
router.get('/:id', (0, auth_middleware_1.requirePermission)('hundi_module', 1), hundi_controller_1.getHundiById);
router.post('/', (0, auth_middleware_1.requirePermission)('hundi_module', 2), hundi_controller_1.createHundi);
router.put('/:id', (0, auth_middleware_1.requirePermission)('hundi_module', 3), hundi_controller_1.updateHundi);
router.delete('/:id', (0, auth_middleware_1.requirePermission)('hundi_module', 4), hundi_controller_1.deleteHundi);
router.put('/:id/finalize', (0, auth_middleware_1.requirePermission)('hundi_module', 2), hundi_controller_1.finalizeHundi);
exports.default = router;
