"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const module_controller_1 = require("../controllers/module.controller");
const router = (0, express_1.Router)();
// router.use(authenticate);
router.get("/", module_controller_1.getModules);
router.get("/:id", module_controller_1.getModuleById);
router.post("/", module_controller_1.createModule);
router.put("/:id", module_controller_1.updateModule);
router.delete("/:id", module_controller_1.deleteModule);
exports.default = router;
